cachedFile = {'json': {'original':None, 'modified': None}}
cachedProcessList = []
cachedObjectTypeList = []
cachedProcesses = {}
cachedObjectTypes = []
cachedActivities = []
cachedObjectTypeMap = None
cachedAttrMap = []
cachedObjectAttrMap = None