cachedFile = {'json': {'original':None, 'modified': None}, 'df': None}
cachedFileInfo = {'filename': '', 'size': 0, 'uploadtime': ''}
cachedProcessList = []
cachedObjectTypeList = []
cachedProcesses = {}
cachedObjectTypes = []
cachedActivities = []
cachedObjectTypeMap = None
cachedAttrMap = []
cachedObjectAttrMap = None
cachedProcessData = []